services:
  desafioavmbapi:
    image: desafioavmbapi
    build:
      context: .
      dockerfile: src/DesafioAVMB.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5126:5126
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
