# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  desafioavmbapi:
    image: desafioavmbapi
    build:
      context: .
      dockerfile: src/DesafioAVMB.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5126:5126
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
