FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5126

ENV ASPNETCORE_URLS=http://+:5126

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/DesafioAVMB.API/DesafioAVMB.API.csproj", "src/DesafioAVMB.API/"]
RUN dotnet restore "src/DesafioAVMB.API/DesafioAVMB.API.csproj"
COPY . .
WORKDIR "/src/src/DesafioAVMB.API"
RUN dotnet build "DesafioAVMB.API.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "DesafioAVMB.API.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DesafioAVMB.API.dll"]
